name: Deploy React to OCI Bucket

on:
  push:
    branches: [ ci/SCRUM-26-pipeline-de-deploy ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build React app
      run: npm run build
      
    - name: Setup OCI CLI
      uses: oracle-actions/configure-oci-cli@v1.0
      with:
        user: ${{ secrets.OCI_USER_ID }}
        fingerprint: ${{ secrets.OCI_FINGERPRINT }}
        tenancy: ${{ secrets.OCI_TENANCY_ID }}
        region: ${{ secrets.OCI_REGION }}
        api_key: ${{ secrets.OCI_API_PRIVATE_KEY }}
        
    - name: Sync build to OCI bucket
      run: |
        oci os object bulk-upload \
          --bucket-name ${{ secrets.OCI_BUCKET_NAME }} \
          --namespace ${{ secrets.OCI_NAMESPACE }} \
          --object-prefix "" \
          --overwrite \
          --exclude "*.map"
